package com.ping.cookbook.dao;

import java.util.List;
import java.util.ArrayList;
import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.SqlUtils;
import de.greenrobot.dao.internal.DaoConfig;
import de.greenrobot.dao.query.Query;
import de.greenrobot.dao.query.QueryBuilder;

import com.ping.cookbook.bean.CookIndex;

import com.ping.cookbook.bean.Step;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "STEP".
*/
public class StepDao extends AbstractDao<Step, Long> {

    public static final String TABLENAME = "STEP";

    /**
     * Properties of entity Step.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Img = new Property(1, String.class, "img", false, "IMG");
        public final static Property Step = new Property(2, String.class, "step", false, "STEP");
        public final static Property IndexId = new Property(3, Long.class, "IndexId", false, "INDEX_ID");
    };

    private DaoSession daoSession;

    private Query<Step> cookIndex_StepsQuery;

    public StepDao(DaoConfig config) {
        super(config);
    }
    
    public StepDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
        this.daoSession = daoSession;
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"STEP\" (" + //
                "\"_id\" INTEGER PRIMARY KEY ," + // 0: id
                "\"IMG\" TEXT," + // 1: img
                "\"STEP\" TEXT," + // 2: step
                "\"INDEX_ID\" INTEGER);"); // 3: IndexId
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"STEP\"";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, Step entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String img = entity.getImg();
        if (img != null) {
            stmt.bindString(2, img);
        }
 
        String step = entity.getStep();
        if (step != null) {
            stmt.bindString(3, step);
        }
 
        Long IndexId = entity.getIndexId();
        if (IndexId != null) {
            stmt.bindLong(4, IndexId);
        }
    }

    @Override
    protected void attachEntity(Step entity) {
        super.attachEntity(entity);
        entity.__setDaoSession(daoSession);
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public Step readEntity(Cursor cursor, int offset) {
        Step entity = new Step( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // img
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // step
            cursor.isNull(offset + 3) ? null : cursor.getLong(offset + 3) // IndexId
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, Step entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setImg(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setStep(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setIndexId(cursor.isNull(offset + 3) ? null : cursor.getLong(offset + 3));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(Step entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(Step entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
    /** Internal query to resolve the "steps" to-many relationship of CookIndex. */
    public List<Step> _queryCookIndex_Steps(Long IndexId) {
        synchronized (this) {
            if (cookIndex_StepsQuery == null) {
                QueryBuilder<Step> queryBuilder = queryBuilder();
                queryBuilder.where(Properties.IndexId.eq(null));
                cookIndex_StepsQuery = queryBuilder.build();
            }
        }
        Query<Step> query = cookIndex_StepsQuery.forCurrentThread();
        query.setParameter(0, IndexId);
        return query.list();
    }

    private String selectDeep;

    protected String getSelectDeep() {
        if (selectDeep == null) {
            StringBuilder builder = new StringBuilder("SELECT ");
            SqlUtils.appendColumns(builder, "T", getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T0", daoSession.getCookIndexDao().getAllColumns());
            builder.append(" FROM STEP T");
            builder.append(" LEFT JOIN COOK_INDEX T0 ON T.\"INDEX_ID\"=T0.\"_id\"");
            builder.append(' ');
            selectDeep = builder.toString();
        }
        return selectDeep;
    }
    
    protected Step loadCurrentDeep(Cursor cursor, boolean lock) {
        Step entity = loadCurrent(cursor, 0, lock);
        int offset = getAllColumns().length;

        CookIndex cookIndex = loadCurrentOther(daoSession.getCookIndexDao(), cursor, offset);
        entity.setCookIndex(cookIndex);

        return entity;    
    }

    public Step loadDeep(Long key) {
        assertSinglePk();
        if (key == null) {
            return null;
        }

        StringBuilder builder = new StringBuilder(getSelectDeep());
        builder.append("WHERE ");
        SqlUtils.appendColumnsEqValue(builder, "T", getPkColumns());
        String sql = builder.toString();
        
        String[] keyArray = new String[] { key.toString() };
        Cursor cursor = db.rawQuery(sql, keyArray);
        
        try {
            boolean available = cursor.moveToFirst();
            if (!available) {
                return null;
            } else if (!cursor.isLast()) {
                throw new IllegalStateException("Expected unique result, but count was " + cursor.getCount());
            }
            return loadCurrentDeep(cursor, true);
        } finally {
            cursor.close();
        }
    }
    
    /** Reads all available rows from the given cursor and returns a list of new ImageTO objects. */
    public List<Step> loadAllDeepFromCursor(Cursor cursor) {
        int count = cursor.getCount();
        List<Step> list = new ArrayList<Step>(count);
        
        if (cursor.moveToFirst()) {
            if (identityScope != null) {
                identityScope.lock();
                identityScope.reserveRoom(count);
            }
            try {
                do {
                    list.add(loadCurrentDeep(cursor, false));
                } while (cursor.moveToNext());
            } finally {
                if (identityScope != null) {
                    identityScope.unlock();
                }
            }
        }
        return list;
    }
    
    protected List<Step> loadDeepAllAndCloseCursor(Cursor cursor) {
        try {
            return loadAllDeepFromCursor(cursor);
        } finally {
            cursor.close();
        }
    }
    

    /** A raw-style query where you can pass any WHERE clause and arguments. */
    public List<Step> queryDeep(String where, String... selectionArg) {
        Cursor cursor = db.rawQuery(getSelectDeep() + where, selectionArg);
        return loadDeepAllAndCloseCursor(cursor);
    }
 
}
