package com.ping.cookbook.dao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.ping.cookbook.bean.CookList;
import com.ping.cookbook.bean.CookIndex;
import com.ping.cookbook.bean.Step;
import com.ping.cookbook.bean.User;

import com.ping.cookbook.dao.CookListDao;
import com.ping.cookbook.dao.CookIndexDao;
import com.ping.cookbook.dao.StepDao;
import com.ping.cookbook.dao.UserDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig cookListDaoConfig;
    private final DaoConfig cookIndexDaoConfig;
    private final DaoConfig stepDaoConfig;
    private final DaoConfig userDaoConfig;

    private final CookListDao cookListDao;
    private final CookIndexDao cookIndexDao;
    private final StepDao stepDao;
    private final UserDao userDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        cookListDaoConfig = daoConfigMap.get(CookListDao.class).clone();
        cookListDaoConfig.initIdentityScope(type);

        cookIndexDaoConfig = daoConfigMap.get(CookIndexDao.class).clone();
        cookIndexDaoConfig.initIdentityScope(type);

        stepDaoConfig = daoConfigMap.get(StepDao.class).clone();
        stepDaoConfig.initIdentityScope(type);

        userDaoConfig = daoConfigMap.get(UserDao.class).clone();
        userDaoConfig.initIdentityScope(type);

        cookListDao = new CookListDao(cookListDaoConfig, this);
        cookIndexDao = new CookIndexDao(cookIndexDaoConfig, this);
        stepDao = new StepDao(stepDaoConfig, this);
        userDao = new UserDao(userDaoConfig, this);

        registerDao(CookList.class, cookListDao);
        registerDao(CookIndex.class, cookIndexDao);
        registerDao(Step.class, stepDao);
        registerDao(User.class, userDao);
    }
    
    public void clear() {
        cookListDaoConfig.getIdentityScope().clear();
        cookIndexDaoConfig.getIdentityScope().clear();
        stepDaoConfig.getIdentityScope().clear();
        userDaoConfig.getIdentityScope().clear();
    }

    public CookListDao getCookListDao() {
        return cookListDao;
    }

    public CookIndexDao getCookIndexDao() {
        return cookIndexDao;
    }

    public StepDao getStepDao() {
        return stepDao;
    }

    public UserDao getUserDao() {
        return userDao;
    }

}
